import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { AlertTriangle, ArrowRight, FileWarning, Home, LogOut, Printer, Scale, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ExportReportButtons } from "@/components/ExportReportButtons";
import { CreditLine } from "@/components/CreditLine";
import { useAuth } from "@/contexts/AuthContext";
import { api } from "@/lib/api";
import { formatCurrency } from "@/lib/format";

const today = new Date();
const currentYear = today.getFullYear();
const defaultFilters = { from_date: `${currentYear}-01-01`, to_date: today.toISOString().slice(0, 10) };

function StatementTable({ testId, section }) {
  return (
    <div className="overflow-x-auto rounded-xl border border-slate-200" data-testid={`${testId}-wrapper`}>
      <Table data-testid={testId}>
        <TableHeader className="bg-slate-950"><TableRow className="hover:bg-slate-950"><TableHead className="text-right text-white">الكود</TableHead><TableHead className="text-right text-white">البيان</TableHead><TableHead className="text-right text-white">مدين</TableHead><TableHead className="text-right text-white">دائن</TableHead><TableHead className="text-right text-white">المبلغ</TableHead><TableHead className="text-right text-white">تفاصيل</TableHead></TableRow></TableHeader>
        <TableBody>
          {(section?.lines || []).length === 0 && <TableRow data-testid={`${testId}-empty-row`}><TableCell colSpan={6} className="py-7 text-center font-bold text-slate-500">لا توجد بيانات</TableCell></TableRow>}
          {(section?.lines || []).map((line, index) => <TableRow key={`${line.code || line.name}-${index}`} data-testid={`${testId}-row-${index}`}><TableCell className="font-extrabold" data-testid={`${testId}-row-${index}-code`}>{line.code || line.entry_number || "-"}</TableCell><TableCell className="font-extrabold" data-testid={`${testId}-row-${index}-name`}>{line.name}</TableCell><TableCell data-testid={`${testId}-row-${index}-debit`}>{line.debit ? formatCurrency(line.debit) : "-"}</TableCell><TableCell data-testid={`${testId}-row-${index}-credit`}>{line.credit ? formatCurrency(line.credit) : "-"}</TableCell><TableCell className="font-extrabold" data-testid={`${testId}-row-${index}-amount`}>{formatCurrency(line.amount)}</TableCell><TableCell data-testid={`${testId}-row-${index}-details`}>{line.details || line.reference || line.entry_date || "-"}</TableCell></TableRow>)}
          <TableRow className="bg-emerald-50 font-extrabold" data-testid={`${testId}-total-row`}><TableCell colSpan={4}>إجمالي {section?.title}</TableCell><TableCell>{formatCurrency(section?.total || 0)}</TableCell><TableCell>-</TableCell></TableRow>
        </TableBody>
      </Table>
    </div>
  );
}

export default function FinancialStatementsPage() {
  const navigate = useNavigate();
  const { user, logout } = useAuth();
  const [report, setReport] = useState(null);
  const [filters, setFilters] = useState(defaultFilters);
  const [loading, setLoading] = useState(true);
  const periodLabel = useMemo(() => `من ${filters.from_date} إلى ${filters.to_date}`, [filters]);

  const loadReport = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (filters.from_date) params.set("from_date", filters.from_date);
      if (filters.to_date) params.set("to_date", filters.to_date);
      const response = await api.get(`/financial-statements?${params.toString()}`);
      setReport(response.data);
      if (response.data.accounting_errors?.length) toast.warning("تم اكتشاف ملاحظات محاسبية في التقرير");
    } catch (error) {
      toast.error("تعذر تحميل القوائم المالية");
    } finally {
      setLoading(false);
    }
  }, [filters]);

  useEffect(() => { loadReport(); }, [loadReport]);

  const balanceDifference = report?.balance_sheet?.check?.total || 0;

  return (
    <main className="min-h-screen bg-slate-50 text-slate-950" data-testid="financial-statements-page">
      <header className="sticky top-0 z-20 border-b border-slate-200/70 bg-white/90 backdrop-blur-xl print:hidden" data-testid="financial-statements-header"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3 px-4 py-4 sm:px-6 lg:px-8"><div className="flex items-center gap-3" data-testid="financial-statements-brand"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-950 text-white"><Scale className="h-5 w-5" /></div><div><p className="text-xs font-extrabold text-emerald-700" data-testid="financial-statements-eyebrow">القوائم المالية</p><h1 className="text-2xl font-extrabold" data-testid="financial-statements-title">الميزانية والمقبوضات والإيرادات</h1></div></div><div className="flex flex-wrap items-center gap-3" data-testid="financial-statements-actions"><Badge className="bg-white text-slate-700" data-testid="financial-statements-organization-badge">{user?.organization_name}</Badge><Button asChild variant="outline" className="h-11 bg-white" data-testid="financial-statements-home-button"><Link to="/"><Home className="h-4 w-4" /> الرئيسية</Link></Button><Button type="button" onClick={() => navigate(-1)} variant="outline" className="h-11 bg-white" data-testid="financial-statements-back-button"><ArrowRight className="h-4 w-4" /> رجوع</Button><Button type="button" onClick={logout} variant="outline" className="h-11 bg-white" data-testid="financial-statements-logout-button"><LogOut className="h-4 w-4" /> خروج</Button></div></div></header>
      <section className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8" data-testid="financial-statements-content">
        <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm print:hidden" data-testid="financial-statements-filters-section"><div className="mb-5 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-2xl font-extrabold" data-testid="financial-statements-filters-title">توليد تلقائي كامل</h2><p className="text-sm font-bold text-slate-500" data-testid="financial-statements-filters-subtitle">يتم استخراج القوائم من القيود اليومية وشجرة الحسابات بدون إدخال يدوي.</p></div><ExportReportButtons title={`القوائم المالية - ${periodLabel}`} fileName={`القوائم-المالية-${filters.from_date}-${filters.to_date}`} selectors={["[data-testid='balance-sheet-section']", "[data-testid='receipts-payments-section']", "[data-testid='revenues-expenses-section']", "[data-testid='accounting-errors-section']"]} disabled={loading || !report} pdfLabel="طباعة PDF" pdfTestId="print-financial-statements-button" excelTestId="export-financial-statements-excel-button" wordTestId="export-financial-statements-word-button" /></div><div className="grid grid-cols-1 gap-4 md:grid-cols-[1fr_1fr_auto]" data-testid="financial-statements-filters-grid"><div><Label data-testid="financial-statements-from-date-label">من تاريخ</Label><Input type="date" value={filters.from_date} onChange={(event) => setFilters((current) => ({ ...current, from_date: event.target.value }))} className="mt-2 h-11 bg-slate-50" data-testid="financial-statements-from-date-input" /></div><div><Label data-testid="financial-statements-to-date-label">إلى تاريخ</Label><Input type="date" value={filters.to_date} onChange={(event) => setFilters((current) => ({ ...current, to_date: event.target.value }))} className="mt-2 h-11 bg-slate-50" data-testid="financial-statements-to-date-input" /></div><Button type="button" onClick={loadReport} className="mt-7 h-11 bg-slate-950 text-white" data-testid="generate-financial-statements-button">تحديث تلقائي</Button></div></section>
        <section className="grid grid-cols-1 gap-4 md:grid-cols-4" data-testid="financial-statements-kpi-grid"><div className="rounded-xl bg-slate-950 p-4 text-white" data-testid="financial-statements-valid-card"><p className="text-xs font-bold text-slate-300">حالة القوائم</p><p className="text-xl font-extrabold" data-testid="financial-statements-valid-value">{report?.is_accounting_valid ? "سليمة" : "بها أخطاء"}</p></div><div className="rounded-xl bg-emerald-50 p-4" data-testid="financial-statements-assets-card"><p className="text-xs font-bold text-emerald-700">إجمالي الأصول</p><p className="text-xl font-extrabold" data-testid="financial-statements-assets-value">{formatCurrency(report?.balance_sheet?.assets?.total || 0)}</p></div><div className="rounded-xl bg-amber-50 p-4" data-testid="financial-statements-result-card"><p className="text-xs font-bold text-amber-700">نتيجة الفترة</p><p className="text-xl font-extrabold" data-testid="financial-statements-result-value">{formatCurrency(report?.revenues_expenses?.result?.total || 0)}</p></div><div className="rounded-xl bg-red-50 p-4" data-testid="financial-statements-errors-card"><p className="text-xs font-bold text-red-700">الأخطاء المكتشفة</p><p className="text-xl font-extrabold" data-testid="financial-statements-errors-value">{report?.accounting_errors?.length || 0}</p></div></section>
        <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm" data-testid="balance-sheet-section"><div className="mb-5 flex flex-col gap-2 lg:flex-row lg:items-center lg:justify-between"><h2 className="text-3xl font-extrabold" data-testid="balance-sheet-title">1- الميزانية</h2><Button type="button" onClick={() => window.print()} variant="outline" className="h-10 bg-white print:hidden" data-testid="print-balance-sheet-button"><Printer className="h-4 w-4" /> طباعة الميزانية</Button></div><div className="grid grid-cols-1 gap-6 xl:grid-cols-2" data-testid="balance-sheet-grid"><div data-testid="balance-sheet-assets"><h3 className="mb-3 text-xl font-extrabold">الأصول</h3><StatementTable testId="balance-sheet-assets-table" section={report?.balance_sheet?.assets} /></div><div className="space-y-5" data-testid="balance-sheet-liabilities-equity"><div><h3 className="mb-3 text-xl font-extrabold">الالتزامات</h3><StatementTable testId="balance-sheet-liabilities-table" section={report?.balance_sheet?.liabilities} /></div><div><h3 className="mb-3 text-xl font-extrabold">حقوق الملكية والفائض</h3><StatementTable testId="balance-sheet-equity-table" section={report?.balance_sheet?.equity} /></div></div></div><div className={`mt-5 rounded-xl border-2 p-5 text-center text-xl font-extrabold ${balanceDifference === 0 ? "border-emerald-600 bg-emerald-50 text-emerald-800" : "border-red-600 bg-red-50 text-red-800"}`} data-testid="balance-sheet-check-box">فرق اتزان الميزانية: {formatCurrency(balanceDifference)}</div></section>
        <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm" data-testid="receipts-payments-section"><div className="mb-5 flex flex-col gap-2 lg:flex-row lg:items-center lg:justify-between"><h2 className="text-3xl font-extrabold" data-testid="receipts-payments-title">2- حساب المقبوضات والمدفوعات</h2><Button type="button" onClick={() => window.print()} variant="outline" className="h-10 bg-white print:hidden" data-testid="print-receipts-payments-button"><WalletCards className="h-4 w-4" /> طباعة</Button></div><div className="grid grid-cols-1 gap-6 xl:grid-cols-2"><div><h3 className="mb-3 text-xl font-extrabold text-emerald-700">المقبوضات</h3><StatementTable testId="receipts-table" section={report?.receipts_payments?.receipts} /></div><div><h3 className="mb-3 text-xl font-extrabold text-red-700">المدفوعات</h3><StatementTable testId="payments-table" section={report?.receipts_payments?.payments} /></div></div><div className="mt-5 rounded-xl bg-slate-950 p-5 text-center text-xl font-extrabold text-white" data-testid="net-cash-flow-box">صافي المقبوضات والمدفوعات: {formatCurrency(report?.receipts_payments?.net_cash_flow?.total || 0)}</div></section>
        <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm" data-testid="revenues-expenses-section"><div className="mb-5 flex flex-col gap-2 lg:flex-row lg:items-center lg:justify-between"><h2 className="text-3xl font-extrabold" data-testid="revenues-expenses-title">3- الإيرادات والمصروفات</h2><Button type="button" onClick={() => window.print()} variant="outline" className="h-10 bg-white print:hidden" data-testid="print-revenues-expenses-button"><Printer className="h-4 w-4" /> طباعة</Button></div><div className="grid grid-cols-1 gap-6 xl:grid-cols-2"><div><h3 className="mb-3 text-xl font-extrabold text-emerald-700">الإيرادات</h3><StatementTable testId="revenues-statement-table" section={report?.revenues_expenses?.revenues} /></div><div><h3 className="mb-3 text-xl font-extrabold text-red-700">المصروفات</h3><StatementTable testId="expenses-statement-table" section={report?.revenues_expenses?.expenses} /></div></div><div className="mt-5 rounded-xl bg-amber-50 p-5 text-center text-xl font-extrabold text-amber-900" data-testid="period-result-box">فائض / عجز الفترة: {formatCurrency(report?.revenues_expenses?.result?.total || 0)}</div></section>
        <section className="rounded-xl border border-red-200 bg-white p-6 shadow-sm" data-testid="accounting-errors-section"><div className="mb-5 flex items-center gap-3"><FileWarning className="h-7 w-7 text-red-700" /><div><h2 className="text-3xl font-extrabold" data-testid="accounting-errors-title">تقرير الأخطاء المحاسبية</h2><p className="text-sm font-bold text-slate-500">يوضح مكان الخطأ بالتفصيل حتى يمكن مراجعته مباشرة.</p></div></div><div className="overflow-x-auto rounded-xl border border-red-100" data-testid="accounting-errors-table-wrapper"><Table data-testid="accounting-errors-table"><TableHeader className="bg-red-900"><TableRow className="hover:bg-red-900"><TableHead className="text-right text-white">الخطورة</TableHead><TableHead className="text-right text-white">نوع الخطأ</TableHead><TableHead className="text-right text-white">مكان الخطأ</TableHead><TableHead className="text-right text-white">التفاصيل</TableHead><TableHead className="text-right text-white">الإجراء المقترح</TableHead></TableRow></TableHeader><TableBody>{(report?.accounting_errors || []).length === 0 && <TableRow data-testid="accounting-errors-empty-row"><TableCell colSpan={5} className="py-8 text-center font-extrabold text-emerald-700">لا توجد أخطاء محاسبية مكتشفة</TableCell></TableRow>}{(report?.accounting_errors || []).map((error, index) => <TableRow key={`${error.error_type}-${index}`} data-testid={`accounting-error-row-${index}`}><TableCell className="font-extrabold" data-testid={`accounting-error-row-${index}-severity`}><AlertTriangle className="ml-1 inline h-4 w-4 text-red-700" />{error.severity === "critical" ? "حرج" : error.severity === "warning" ? "تنبيه" : "معلومة"}</TableCell><TableCell data-testid={`accounting-error-row-${index}-type`}>{error.error_type}</TableCell><TableCell className="font-extrabold" data-testid={`accounting-error-row-${index}-location`}>{error.location}</TableCell><TableCell data-testid={`accounting-error-row-${index}-details`}>{error.details}</TableCell><TableCell data-testid={`accounting-error-row-${index}-fix`}>{error.suggested_fix || "-"}</TableCell></TableRow>)}</TableBody></Table></div></section>
      </section><footer className="px-4 pb-5 print:hidden"><CreditLine testId="financial-statements-creator-credit" /></footer>
    </main>
  );
}